remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

#title: Lorem ipsum dolor sit amet
#description: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tem
